@ECHO OFF
SETLOCAL
SET "SCRIPT_DIR=%~dp0"
SET "GEMINI_HOME=%SCRIPT_DIR%gemini-home"
SET "REAL_LOCALAPPDATA=%LOCALAPPDATA%"
SET "HOME=%GEMINI_HOME%"
SET "USERPROFILE=%GEMINI_HOME%"
SET "APPDATA=%GEMINI_HOME%\AppData\Roaming"
SET "LOCALAPPDATA=%REAL_LOCALAPPDATA%"
SET "GEMINI_CLI_NO_RELAUNCH=true"
SET "GOOGLE_GENAI_USE_GCA=true"
IF NOT EXIST "%HOME%" MKDIR "%HOME%"
IF NOT EXIST "%HOME%\.gemini" MKDIR "%HOME%\.gemini"
WHERE gemini.cmd >NUL 2>NUL
IF ERRORLEVEL 1 (
  ECHO gemini.cmd was not found in PATH. Install Gemini CLI or add it to PATH. 1>&2
  EXIT /B 1
)
CALL gemini.cmd %*
EXIT /B %ERRORLEVEL%
